[package]
name = "phil"
version = "2.0.0"
authors = ["Sam Kirby <sam.kirby94@hotmail.co.uk>"]
edition = "2021"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
anyhow = "1"
rand = "0.8"
serde_json = "1"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-futures = "0.2"
twilight-model = "0.9"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird.git"
branch = "next"
default-features = false
features = ["yt-dlp", "driver", "twilight-rustls", "zlib-simd"]

[dependencies.time]
version = "0.3"
features = ["serde"]

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "sync"]

[dependencies.twilight-gateway]
version = "0.9"
default-features = false
features = ["rustls-webpki-roots", "simd-json", "zlib-simd", "tracing"]

[dependencies.twilight-http]
version = "0.9"
default-features = false
features = ["rustls-webpki-roots", "simd-json", "tracing"]

[dependencies.twilight-util]
version = "0.9"
features = ["full"]
